/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cosmolustosa.view;

import java.awt.Dialog;

/**
 *
 * @author Anonymous
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        boasVindas = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jButtonPacienteEnfermeira = new javax.swing.JButton();
        jButtonUser = new javax.swing.JButton();
        jButtonMedico = new javax.swing.JButton();
        jButtonPaciente = new javax.swing.JButton();
        jLabelImgInterna = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemMedicos = new javax.swing.JMenuItem();
        jMenuItemPacientes = new javax.swing.JMenuItem();
        jMenuItemEnfermeiras = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBoasVindas = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MedSoft");
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setName("Tela Principal"); // NOI18N
        getContentPane().setLayout(null);

        boasVindas.setClosable(true);
        boasVindas.setTitle("Boas Vindas");
        boasVindas.setVisible(true);
        boasVindas.getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jButtonPacienteEnfermeira.setBackground(new java.awt.Color(153, 102, 255));
        jButtonPacienteEnfermeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/enf2.png"))); // NOI18N
        jButtonPacienteEnfermeira.setText("Enfermeoras");
        jButtonPacienteEnfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteEnfermeiraActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPacienteEnfermeira);
        jButtonPacienteEnfermeira.setBounds(10, 160, 120, 60);

        jButtonUser.setBackground(new java.awt.Color(153, 102, 255));
        jButtonUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/user.png"))); // NOI18N
        jButtonUser.setText("Usuário");
        jButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUser);
        jButtonUser.setBounds(10, 230, 120, 60);

        jButtonMedico.setBackground(new java.awt.Color(153, 102, 255));
        jButtonMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/med11.png"))); // NOI18N
        jButtonMedico.setText("Médicos");
        jButtonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMedico);
        jButtonMedico.setBounds(10, 90, 120, 60);

        jButtonPaciente.setBackground(new java.awt.Color(153, 102, 255));
        jButtonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/med5.png"))); // NOI18N
        jButtonPaciente.setText("Paciente");
        jButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPaciente);
        jButtonPaciente.setBounds(10, 20, 120, 60);

        jLabelImgInterna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/engre3.jpg"))); // NOI18N
        jPanel1.add(jLabelImgInterna);
        jLabelImgInterna.setBounds(0, 0, 730, 320);

        boasVindas.getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 30, 710, 320);

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("Sistema de Gerenciamento de Clínicas Médicas");
        boasVindas.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 420, 16);

        getContentPane().add(boasVindas);
        boasVindas.setBounds(40, 10, 760, 430);

        jMenuBar1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N

        jMenuCadastro.setText("Cadastro");

        jMenuItemMedicos.setText("Médicos");
        jMenuItemMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemMedicos);

        jMenuItemPacientes.setText("Pacientes");
        jMenuCadastro.add(jMenuItemPacientes);

        jMenuItemEnfermeiras.setText("Enfermeira(o)");
        jMenuItemEnfermeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnfermeirasActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemEnfermeiras);

        jMenuItemUsuarios.setText("Usuários");
        jMenuCadastro.add(jMenuItemUsuarios);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorios.setText("Relatorios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBoasVindas.setText("Tela de Boas Vindas");
        jMenuItemTelaBoasVindas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBoasVindasActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBoasVindas);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(873, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicosActionPerformed
        TelaMedico tm = new TelaMedico();
        tm.setTitle("Cad. Médicos");
        tm.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItemMedicosActionPerformed

    private void jMenuItemEnfermeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnfermeirasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEnfermeirasActionPerformed

    private void jMenuItemTelaBoasVindasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBoasVindasActionPerformed
        boasVindas.setVisible(true);
       
        
    }//GEN-LAST:event_jMenuItemTelaBoasVindasActionPerformed

    private void jButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPacienteActionPerformed

    private void jButtonPacienteEnfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteEnfermeiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPacienteEnfermeiraActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicoActionPerformed
       TelaMedico tm = new TelaMedico();
       tm.setTitle("Cad. Médicos");
       tm.setVisible(true);
      
    }//GEN-LAST:event_jButtonMedicoActionPerformed

    private void jButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUserActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame boasVindas;
    private javax.swing.JButton jButtonMedico;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JButton jButtonPacienteEnfermeira;
    private javax.swing.JButton jButtonUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImgInterna;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemEnfermeiras;
    private javax.swing.JMenuItem jMenuItemMedicos;
    private javax.swing.JMenuItem jMenuItemPacientes;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBoasVindas;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
